baseURL = 'https://warrenagee.github.io/'
languageCode = 'en-us'
title = 'Warrens Hugo Site'

# Deployment details
[deployment]

  [[deployment.targets]]
    name = "warren-hugo-test"
    URL = "s3://warren-hugo-test?region=us-west-2"

    # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
    cloudFrontDistributionID =	"EQZP2Q58OHZJ3"

  [[deployment.matchers]]
    # Cache static assets for 20 years.
    pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
    cacheControl = "max-age=630720000, no-transform, public"
    gzip = true

  [[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json)$"
    gzip = true
